from __future__ import annotations

from dog_remote_tool.modules.navigation import arc_commands as _arc_commands
from dog_remote_tool.modules.navigation import camera_overlay as _camera_overlay
from dog_remote_tool.modules.navigation import control_commands as _control_commands
from dog_remote_tool.modules.navigation import goal_commands as _goal_commands
from dog_remote_tool.modules.navigation import helper_commands as _helper_commands
from dog_remote_tool.modules.navigation import helper_scripts as _helper_scripts
from dog_remote_tool.modules.navigation import map_commands as _map_commands
from dog_remote_tool.modules.navigation import payloads as _payloads
from dog_remote_tool.modules.navigation import probe as _probe
from dog_remote_tool.modules.navigation import status as _status
from dog_remote_tool.modules.body_navigation_bridge import release_body_navigation_bridge_command


ALG_MANAGER_APP_MSG_PORT = 10010
ALG_MANAGER_SDK_MSG_PORT = 10014
DEFAULT_NAV_LATERAL_SPEED = _payloads.DEFAULT_NAV_LATERAL_SPEED
DEFAULT_NAV_ANGULAR_SPEED = _payloads.DEFAULT_NAV_ANGULAR_SPEED
MODE_SWITCH_TOPIC = _helper_scripts.MODE_SWITCH_TOPIC
NAVIGATION_IDLE_TERMINAL_STATES = _map_commands.NAVIGATION_IDLE_TERMINAL_STATES
# 201 can appear while the navigation BT is still waiting/recovering after a
# blocked route. Only the pre-start cleanup treats it as idle; the background
# release watcher must not turn that intermediate state into a cancellation.
NAVIGATION_RELEASE_TERMINAL_STATES = _helper_commands.NAVIGATION_RELEASE_TERMINAL_STATES
NAV_CAMERA_OVERLAY_MARKER = _camera_overlay.NAV_CAMERA_OVERLAY_MARKER
START_NAV_HELPER_SCRIPT = _helper_scripts.START_NAV_HELPER_SCRIPT
START_NAV_HELPER_PID = _helper_scripts.START_NAV_HELPER_PID
START_NAV_HELPER_FIFO = _helper_scripts.START_NAV_HELPER_FIFO
START_NAV_HELPER_LOG = _helper_scripts.START_NAV_HELPER_LOG
ALG_MANAGER_CONFIGS = (
    "/opt/robot/robot-alg-manager/config/alg_manager_arc_mid.yaml",
    "/opt/robot/robot-alg-manager/config/alg_manager_mid.yaml",
    "/opt/robot/robot-alg-manager/config/alg_manager_arc.yaml",
    "/opt/robot/robot-alg-manager/config/alg_manager.yaml",
)
NAVIGATION_STATE_TEXT = _status.NAVIGATION_STATE_TEXT
ACTIVE_SUBSTATE_TEXT = _status.ACTIVE_SUBSTATE_TEXT
TASK_STATUS_TEXT = _status.TASK_STATUS_TEXT
LOCALIZATION_STATE_TEXT = _status.LOCALIZATION_STATE_TEXT
PERCEPTION_STATE_TEXT = _status.PERCEPTION_STATE_TEXT
navigation_state_text = _status.navigation_state_text
active_substate_text = _status.active_substate_text
task_status_text = _status.task_status_text
localization_state_text = _status.localization_state_text
localization_state_display_text = _status.localization_state_display_text
perception_state_text = _status.perception_state_text
navigation_user_status_summary = _status.navigation_user_status_summary
parse_key_values = _status.parse_key_values
summarize_status = _status.summarize_status
probe_status_command = _probe.probe_status_command
fast_probe_status_command = _probe.fast_probe_status_command
status_command = _probe.status_command
navigation_camera_overlay_stream_command = _camera_overlay.navigation_camera_overlay_stream_command


alg_manager_ws_request_payload = _payloads.alg_manager_ws_request_payload
alg_manager_start_multi_nav_by_points_payload = _payloads.alg_manager_start_multi_nav_by_points_payload
alg_manager_start_multi_nav_task_route_value = _payloads.alg_manager_start_multi_nav_task_route_value
map_id_from_map_path = _payloads.map_id_from_map_path
default_goal_map_path = _payloads.default_goal_map_path
_navigation_2d_map_path = _payloads._navigation_2d_map_path
_initialize_payload = _payloads._initialize_payload
_goal_payload = _payloads._goal_payload
_goal_task_payload = _payloads._goal_task_payload
_goals_payload = _payloads._goals_payload
_pose_yaml = _payloads._pose_yaml
_route_points_with_forward_yaw = _payloads._route_points_with_forward_yaw
_command_payload = _payloads._command_payload
_payload_b64 = _payloads._payload_b64
_start_arc_calibration_payload = _payloads._start_arc_calibration_payload
_map_path_prefix = _payloads._map_path_prefix
_start_navigation_helper_python = _helper_scripts._start_navigation_helper_python
_ensure_start_navigation_helper_inner = _helper_commands._ensure_start_navigation_helper_inner
_publish_start_navigation_payload_inner = _helper_commands._publish_start_navigation_payload_inner
ensure_navigation_helpers_command = _helper_commands.ensure_navigation_helpers_command
ensure_mode_switch_helper_command = _helper_commands.ensure_mode_switch_helper_command
_cleanup_pid_helper_inner = _helper_commands._cleanup_pid_helper_inner
cleanup_navigation_tool_helpers_inner = _helper_commands.cleanup_navigation_tool_helpers_inner
cleanup_navigation_tool_helpers_command = _helper_commands.cleanup_navigation_tool_helpers_command
_mode_switch_inner = _helper_commands._mode_switch_inner
_alg_manager_stop_nav_inner = _helper_commands._alg_manager_stop_nav_inner
_alg_manager_control_owner_inner = _helper_commands._alg_manager_control_owner_inner
_body_navigation_right_inner = _helper_commands._body_navigation_right_inner
_ensure_body_navigation_bridge_command = _helper_commands._ensure_body_navigation_bridge_command
_navigation_start_ssh_command = _helper_commands._navigation_start_ssh_command
_release_navigation_control_inner = _helper_commands._release_navigation_control_inner
_release_navigation_control_when_done_inner = _helper_commands._release_navigation_control_when_done_inner
_stop_navigation_loop_inner = _helper_commands._stop_navigation_loop_inner
load_map_command = _map_commands.load_map_command
prepare_map_command = _map_commands.prepare_map_command
_load_navigation_map_inner = _map_commands._load_navigation_map_inner
_load_localization_map_once_inner = _map_commands._load_localization_map_once_inner
_navigation_2d_map_gate_inner = _map_commands._navigation_2d_map_gate_inner
_publish_navigation_task_inner = _map_commands._publish_navigation_task_inner
_pre_start_navigation_mode_inner = _map_commands._pre_start_navigation_mode_inner
_wait_navigation_active_after_start_inner = _map_commands._wait_navigation_active_after_start_inner
_wait_navigation_standby_after_initialize_inner = _map_commands._wait_navigation_standby_after_initialize_inner
_fast_navigation_header = _map_commands._fast_navigation_header
_update_route_graph_inner = _map_commands._update_route_graph_inner
_clear_busy_navigation_before_goal_inner = _map_commands._clear_busy_navigation_before_goal_inner
start_goal_command = _goal_commands.start_goal_command
start_multipoint_command = _goal_commands.start_multipoint_command
start_multipoint_loop_command = _goal_commands.start_multipoint_loop_command
start_route_goal_command = _goal_commands.start_route_goal_command
start_route_goal_loop_command = _goal_commands.start_route_goal_loop_command


start_arc_with_map_command = _arc_commands.start_arc_with_map_command
start_arc_calibration_command = _arc_commands.start_arc_calibration_command
mark_charging_dock_command = _arc_commands.mark_charging_dock_command
navigation_control_command = _control_commands.navigation_control_command
pause_command = _control_commands.pause_command
continue_command = _control_commands.continue_command
stop_command = _control_commands.stop_command
