from __future__ import annotations

from PyQt5.QtCore import QEasingCurve, QPropertyAnimation, Qt
from PyQt5.QtWidgets import (
    QAbstractItemView,
    QFrame,
    QGridLayout,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QListWidget,
    QPushButton,
    QProgressBar,
    QSizePolicy,
    QSplitter,
    QTableWidget,
    QHeaderView,
    QVBoxLayout,
    QWidget,
)


class BagLayoutSectionsMixin:
    def _build_page_header(self) -> QFrame:
        header = QFrame()
        header.setObjectName("PageHeader")
        header_layout = QVBoxLayout(header)
        header_layout.setContentsMargins(16, 10, 16, 10)
        title = QLabel("远程录包")
        title.setObjectName("AppTitle")
        subtitle = QLabel("录制、回传、校验、清理")
        subtitle.setObjectName("Muted")
        subtitle.setWordWrap(True)
        header_layout.addWidget(title)
        header_layout.addWidget(subtitle)
        return header

    def _build_record_status_box(self) -> QFrame:
        status_box = QFrame()
        status_box.setObjectName("BagStatusBar")
        status_box.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        status_layout = QHBoxLayout(status_box)
        status_layout.setContentsMargins(12, 8, 12, 8)
        status_layout.setSpacing(10)
        status_info = QFrame()
        status_info.setObjectName("BagStatusInfo")
        status_info.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        status_info_layout = QVBoxLayout(status_info)
        status_info_layout.setContentsMargins(12, 8, 12, 8)
        status_info_layout.setSpacing(0)
        status_line = QHBoxLayout()
        status_line.setSpacing(8)
        status_actions = QGridLayout()
        status_actions.setContentsMargins(0, 0, 0, 0)
        status_actions.setHorizontalSpacing(8)
        status_actions.setVerticalSpacing(8)
        status_title = QLabel("录包作业台")
        status_title.setObjectName("StatusStrong")
        self.topic_check_label = QLabel("")
        self.topic_check_label.setObjectName("BagStatusWarn")
        self.topic_check_label.setMinimumWidth(0)
        self.topic_check_label.setSizePolicy(QSizePolicy.Maximum, QSizePolicy.Preferred)
        self.topic_check_label.setVisible(False)
        self.topic_check_btn = QPushButton("话题检查")
        self.topic_check_btn.setObjectName("SoftPrimary")
        self.topic_check_btn.setToolTip("检查当前选中主题的 Topic 是否有数据")
        self.topic_check_btn.clicked.connect(self.check_selected_topics)
        self.remote_topic_btn = QPushButton("远端Topic")
        self.remote_topic_btn.setObjectName("SoftPrimary")
        self.remote_topic_btn.setToolTip("打开远端全部Topic列表，并采样显示实时Hz")
        self.remote_topic_btn.clicked.connect(self.show_remote_topic_dialog)
        self.record_status_label = QLabel("就绪")
        self.record_status_label.setObjectName("StatusStrong")
        self.record_status_label.setMinimumWidth(0)
        self.record_status_label.setSizePolicy(QSizePolicy.Ignored, QSizePolicy.Preferred)
        self.duration_label = QLabel("00:00:00")
        self.duration_label.setObjectName("MetricValue")
        self.current_bag_label = QLabel("无")
        self.current_bag_label.setObjectName("StatusStrong")
        self.current_bag_label.setMinimumWidth(0)
        self.current_bag_label.setSizePolicy(QSizePolicy.Ignored, QSizePolicy.Preferred)
        self.current_bag_size_label = QLabel("--")
        self.current_bag_size_label.setObjectName("MetricValue")
        self.progress_bar = QProgressBar()
        self.progress_bar.setRange(0, 100)
        self.progress_bar.setTextVisible(False)
        self.progress_bar.setObjectName("BagTransferProgress")
        self.progress_bar.setMinimumWidth(220)
        self.progress_bar.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        self.progress_bar.setVisible(False)
        self.progress_animation = QPropertyAnimation(self.progress_bar, b"value", self)
        self.progress_animation.setDuration(220)
        self.progress_animation.setEasingCurve(QEasingCurve.OutCubic)
        self.transfer_percent_label = QLabel("--")
        self.transfer_percent_label.setObjectName("BagTransferPercent")
        self.transfer_speed_label = QLabel("速度 --")
        self.transfer_speed_label.setObjectName("BagTransferSpeed")
        self.transfer_speed_label.setMinimumWidth(116)
        self.transfer_speed_label.setAlignment(Qt.AlignRight | Qt.AlignVCenter)
        self.transfer_speed_label.setVisible(False)
        self.transfer_percent_label.setVisible(False)
        self.transfer_eta_label = QLabel("预计 --")
        self.transfer_eta_label.setObjectName("BagTransferEta")
        self.transfer_eta_label.setMinimumWidth(92)
        self.transfer_eta_label.setAlignment(Qt.AlignCenter)
        self.transfer_eta_label.setVisible(False)
        self.start_btn = QPushButton("开始录制")
        self.start_btn.setObjectName("Primary")
        self.start_btn.clicked.connect(self.start_recording)
        self.resume_btn = QPushButton("接管录制")
        self.resume_btn.setObjectName("SoftPrimary")
        self.resume_btn.setToolTip("检测远端仍在运行的 ros2 bag record，并恢复到当前录制状态")
        self.resume_btn.setEnabled(False)
        self.resume_btn.clicked.connect(self.resume_remote_recording)
        self.stop_btn = QPushButton("停止录制")
        self.stop_btn.setObjectName("Danger")
        self.stop_btn.setEnabled(False)
        self.stop_btn.clicked.connect(self.stop_recording)
        for button in (self.start_btn, self.resume_btn, self.stop_btn):
            button.setMinimumWidth(96)
            button.setMinimumHeight(42)
            button.setSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        self.record_detail_widget = QWidget()
        self.record_detail_widget.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        record_detail_layout = QHBoxLayout(self.record_detail_widget)
        record_detail_layout.setContentsMargins(0, 0, 0, 0)
        record_detail_layout.setSpacing(8)
        self.current_bag_title_label = QLabel("Bag")
        self.current_bag_size_title_label = QLabel("大小")
        record_detail_layout.addWidget(self.duration_label)
        record_detail_layout.addWidget(self.current_bag_title_label)
        record_detail_layout.addWidget(self.current_bag_label, 1)
        record_detail_layout.addWidget(self.current_bag_size_title_label)
        record_detail_layout.addWidget(self.current_bag_size_label)
        self.record_detail_widget.setVisible(True)
        status_line.addWidget(status_title)
        status_line.addWidget(self.record_status_label)
        status_line.addWidget(self.record_detail_widget, 3)
        status_line.addWidget(self.progress_bar, 2)
        status_line.addWidget(self.transfer_percent_label)
        status_line.addWidget(self.transfer_speed_label)
        status_line.addWidget(self.transfer_eta_label)
        status_line.addWidget(self.topic_check_label)
        status_info_layout.addLayout(status_line)
        status_actions.addWidget(self.start_btn, 0, 0)
        status_actions.addWidget(self.resume_btn, 0, 1)
        status_actions.addWidget(self.stop_btn, 0, 2)
        status_actions.setColumnStretch(0, 1)
        status_actions.setColumnStretch(1, 1)
        status_actions.setColumnStretch(2, 1)
        status_layout.addWidget(status_info, 1)
        status_layout.addLayout(status_actions)
        return status_box

    def _build_topic_panel(self) -> QWidget:
        left_widget = QWidget()
        left_widget.setMinimumWidth(0)
        left_widget.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        left = QVBoxLayout(left_widget)
        left.setContentsMargins(0, 0, 0, 0)
        left.setSpacing(12)

        topic_box = QFrame()
        topic_box.setObjectName("BagMainPanel")
        topic_box.setMinimumWidth(0)
        topic_box.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        topic_layout = QVBoxLayout(topic_box)
        topic_layout.setContentsMargins(16, 14, 16, 16)
        topic_layout.setSpacing(12)
        topic_header = QHBoxLayout()
        topic_title = QLabel("常用录制模板")
        topic_title.setObjectName("DiagSectionTitle")
        self.selected_count_label = QLabel("已选择: 0 个主题")
        self.selected_count_label.setObjectName("FieldLabel")
        self.preview_count_label = QLabel("当前录制Topic: 0 个")
        self.preview_count_label.setObjectName("FieldLabel")
        topic_header.addWidget(topic_title)
        topic_header.addStretch(1)
        self.topic_editor_toggle = QPushButton("编辑 Topic")
        self.topic_editor_toggle.setObjectName("SoftPrimary")
        self.topic_editor_toggle.setCheckable(True)
        topic_header.addWidget(self.topic_check_btn)
        topic_header.addWidget(self.remote_topic_btn)
        topic_header.addWidget(self.topic_editor_toggle)
        topic_header.addWidget(self.selected_count_label)
        topic_header.addWidget(self.preview_count_label)
        topic_layout.addLayout(topic_header)

        topic_splitter = QSplitter(Qt.Horizontal)
        topic_splitter.setChildrenCollapsible(False)
        topic_splitter.setMinimumWidth(0)
        topic_splitter.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        topic_layout.addWidget(topic_splitter, 1)

        theme_panel = QWidget()
        theme_panel.setMinimumWidth(0)
        theme_panel.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        topic_left = QVBoxLayout(theme_panel)
        topic_left.setContentsMargins(0, 0, 0, 0)
        topic_left.setSpacing(7)

        topic_controls_height = 112
        theme_controls_panel = QFrame()
        theme_controls_panel.setObjectName("BagEditorPanel")
        theme_controls_panel.setMinimumHeight(topic_controls_height)
        theme_controls_layout = QVBoxLayout(theme_controls_panel)
        theme_controls_layout.setContentsMargins(10, 9, 10, 10)
        theme_controls_layout.setSpacing(6)
        topic_buttons = QGridLayout()
        topic_buttons.setHorizontalSpacing(6)
        topic_buttons.setVerticalSpacing(6)
        theme_actions = (
            ("新增", self.create_custom_theme, "SoftPrimary", 0, 0),
            ("删除", self.delete_active_theme, "SoftDanger", 0, 1),
            ("全选", self.select_all_topics, "", 1, 0),
            ("清空", self.deselect_all_topics, "", 1, 1),
        )
        for label, slot, object_name, row, column in theme_actions:
            btn = QPushButton(label)
            btn.setMinimumWidth(0)
            if object_name:
                btn.setObjectName(object_name)
            btn.clicked.connect(slot)
            topic_buttons.addWidget(btn, row, column)
        topic_buttons.setColumnStretch(0, 1)
        topic_buttons.setColumnStretch(1, 1)
        theme_controls_layout.addLayout(topic_buttons)
        topic_left.addWidget(theme_controls_panel)
        self.topic_list = QListWidget()
        self.topic_list.setSelectionMode(QAbstractItemView.ExtendedSelection)
        self.topic_list.setMinimumHeight(260)
        self.topic_list.setMinimumWidth(0)
        self.topic_list.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        self.topic_list.setUniformItemSizes(True)
        self.topic_list.itemSelectionChanged.connect(self._topic_selection_changed)
        self.topic_list.currentItemChanged.connect(lambda _current, _previous: self._refresh_active_topic_label())
        topic_left.addWidget(self.topic_list)

        topic_splitter.addWidget(theme_panel)

        topic_panel = QWidget()
        topic_panel.setMinimumWidth(0)
        topic_panel.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        preview_layout = QVBoxLayout(topic_panel)
        preview_layout.setContentsMargins(0, 0, 0, 0)
        preview_layout.setSpacing(7)

        self.topic_editor_panel = QFrame()
        self.topic_editor_panel.setObjectName("BagEditorPanel")
        self.topic_editor_panel.setMinimumHeight(topic_controls_height)
        editor_layout = QVBoxLayout(self.topic_editor_panel)
        editor_layout.setContentsMargins(10, 9, 10, 10)
        editor_layout.setSpacing(8)

        name_row = QHBoxLayout()
        name_row.setSpacing(7)
        self.active_topic_label = QLabel("当前主题: -")
        self.active_topic_label.setObjectName("FieldLabel")
        self.active_topic_label.setMinimumWidth(0)
        self.active_topic_label.setSizePolicy(QSizePolicy.Ignored, QSizePolicy.Preferred)
        self.topic_name_entry = QLineEdit()
        self.topic_name_entry.setPlaceholderText("主题显示名称")
        save_topic_name = QPushButton("保存名称")
        save_topic_name.setObjectName("SoftPrimary")
        save_topic_name.clicked.connect(self.save_active_topic_name)
        name_row.addWidget(self.active_topic_label)
        name_row.addWidget(self.topic_name_entry, 1)
        name_row.addWidget(save_topic_name)
        editor_layout.addLayout(name_row)

        edit_row = QHBoxLayout()
        edit_row.setSpacing(7)
        self.topic_entry = QLineEdit()
        self.topic_entry.setPlaceholderText("输入 /topic_name")
        add_topic = QPushButton("添加")
        add_topic.setObjectName("SoftPrimary")
        add_topic.clicked.connect(self.add_topic_to_active_theme)
        remove_topic = QPushButton("移除选中")
        remove_topic.setObjectName("SoftDanger")
        remove_topic.clicked.connect(self.remove_selected_topics_from_active_theme)
        edit_row.addWidget(self.topic_entry, 1)
        edit_row.addWidget(add_topic)
        edit_row.addWidget(remove_topic)
        editor_layout.addLayout(edit_row)

        self.topic_editor_panel.hide()
        self.topic_editor_toggle.toggled.connect(self.topic_editor_panel.setVisible)
        self.topic_editor_toggle.toggled.connect(
            lambda checked: self.topic_editor_toggle.setText("收起编辑" if checked else "编辑 Topic")
        )
        preview_layout.addWidget(self.topic_editor_panel)

        self.topic_table = QTableWidget(0, 1)
        self.topic_table.setHorizontalHeaderLabels(["Topic"])
        self.topic_table.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.topic_table.setSelectionMode(QAbstractItemView.ExtendedSelection)
        self.topic_table.setAlternatingRowColors(True)
        self.topic_table.verticalHeader().setVisible(False)
        self.topic_table.verticalHeader().setDefaultSectionSize(30)
        self.topic_table.horizontalHeader().setVisible(False)
        self.topic_table.horizontalHeader().setStretchLastSection(True)
        self.topic_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.Stretch)
        self.topic_table.setWordWrap(False)
        self.topic_table.setMinimumHeight(260)
        self.topic_table.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        self.topic_table.itemChanged.connect(self._topic_table_changed)
        preview_layout.addWidget(self.topic_table)

        topic_splitter.addWidget(topic_panel)
        topic_splitter.setStretchFactor(0, 2)
        topic_splitter.setStretchFactor(1, 3)
        topic_splitter.setSizes([330, 720])
        left.addWidget(topic_box, 1)
        return left_widget
