from __future__ import annotations

import dog_remote_tool.modules.mapping.arc as _mapping_arc
import dog_remote_tool.modules.mapping.alg as _mapping_alg
from dog_remote_tool.modules.mapping import defaults as mapping_defaults
import dog_remote_tool.modules.mapping.pgm_editor as _mapping_pgm_editor
import dog_remote_tool.modules.mapping.probe as _mapping_probe
import dog_remote_tool.modules.mapping.status as _mapping_status
import dog_remote_tool.modules.mapping.transfer as _mapping_transfer


DEFAULT_SENSOR_TYPE = mapping_defaults.DEFAULT_SENSOR_TYPE
DEFAULT_SAVE_MAP_PATH = mapping_defaults.DEFAULT_SAVE_MAP_PATH
OTA_SAVE_MAP_PATH = mapping_defaults.OTA_SAVE_MAP_PATH
DEFAULT_HISTORY_MAP_PATH = mapping_defaults.DEFAULT_HISTORY_MAP_PATH
DEFAULT_CALIBRATION_FILE_PATH = mapping_defaults.DEFAULT_CALIBRATION_FILE_PATH
DEFAULT_ARC_CALIBRATION_FILE_PATH = mapping_defaults.DEFAULT_ARC_CALIBRATION_FILE_PATH
DEFAULT_LOCAL_DATA_ROOT = mapping_defaults.DEFAULT_LOCAL_DATA_ROOT
DEFAULT_LOCAL_MAP_DIR = mapping_defaults.DEFAULT_LOCAL_MAP_DIR
delete_history_map_command = _mapping_transfer.delete_history_map_command
list_map_pgm_command = _mapping_transfer.list_map_pgm_command
fetch_map_preview_files_command = _mapping_transfer.fetch_map_preview_files_command
upload_edited_map_pgm_command = _mapping_pgm_editor.upload_edited_map_pgm_command
is_mapping_alg_status = _mapping_status.is_mapping_alg_status
is_mapping_active_alg_status = _mapping_status.is_mapping_active_alg_status
mapping_status_from_alg_status = _mapping_status.mapping_status_from_alg_status
alg_mapping_status = _mapping_alg.alg_mapping_status
alg_mapping_status_inner = _mapping_alg.alg_mapping_status_inner
alg_probe_status_command = _mapping_alg.alg_probe_status_command
alg_start_mapping_command = _mapping_alg.alg_start_mapping_command
alg_finish_mapping_command = _mapping_alg.alg_finish_mapping_command
alg_cancel_mapping_command = _mapping_alg.alg_cancel_mapping_command
probe_status_command = _mapping_probe.probe_status_command
start_mapping_command = _mapping_alg.alg_start_mapping_command
cancel_mapping_command = _mapping_alg.alg_cancel_mapping_command

default_sensor_type = mapping_defaults.default_sensor_type
default_save_map_path = mapping_defaults.default_save_map_path
default_calibration_file_path = mapping_defaults.default_calibration_file_path
default_arc_calibration_file_path = mapping_defaults.default_arc_calibration_file_path
default_map_pcd_path = mapping_defaults.default_map_pcd_path
history_map_path = mapping_defaults.history_map_path

ARC_DOCK_STATE_TEXT = _mapping_arc.ARC_DOCK_STATE_TEXT
ARC_STATE_TEXT = _mapping_arc.ARC_STATE_TEXT
ARC_ACTIONS = _mapping_arc.ARC_ACTIONS
arc_runtime_profile = _mapping_arc.arc_runtime_profile
arc_status_snapshot_command = _mapping_arc.arc_status_snapshot_command
arc_start_action_command = _mapping_arc.arc_start_action_command
arc_release_control_command = _mapping_arc.arc_release_control_command
finish_mapping_command = _mapping_alg.alg_finish_mapping_command
