from __future__ import annotations

from dog_remote_tool.modules import mapping
import dog_remote_tool.modules.localization.io as _localization_io
import dog_remote_tool.modules.localization.alg as _localization_alg
import dog_remote_tool.modules.localization.probe as _localization_probe
import dog_remote_tool.modules.localization.runtime as _localization_runtime


DEFAULT_MAP_PCD_PATH = mapping.default_map_pcd_path()
REMOTE_POSE_RECORD = _localization_runtime.REMOTE_POSE_RECORD
REMOTE_POSE_RECORD_PID = _localization_runtime.REMOTE_POSE_RECORD_PID
REMOTE_POSE_RECORD_LOG = _localization_runtime.REMOTE_POSE_RECORD_LOG

fetch_pose_record_command = _localization_io.fetch_pose_record_command
fetch_map_files_command = _localization_io.fetch_map_files_command
list_localization_map_pgm_command = _localization_io.list_localization_map_pgm_command
pose_probe_command = _localization_io.pose_probe_command
pose_stream_command = _localization_io.pose_stream_command
navigation_plan_stream_command = _localization_io.navigation_plan_stream_command
obstacle_stream_command = _localization_io.obstacle_stream_command
alg_localization_load_inner = _localization_alg.alg_localization_load_inner
map_id_from_map_pcd_path = _localization_alg.map_id_from_map_pcd_path
probe_status_command = _localization_probe.probe_status_command
start_localization_command = _localization_runtime.start_localization_command
test_localization_once_command = _localization_runtime.test_localization_once_command
stop_localization_command = _localization_runtime.stop_localization_command


def status_command(profile):
    return _localization_probe.status_command(profile)
