from __future__ import annotations


def s100_usb_diagnosis_lines() -> list[str]:
    return [
        's100_report_usb_state() {',
        '  echo "[flash] S100 USB 状态摘要:"',
        '  local usb_list=""',
        '  if [ -n "${FASTBOOT_DEVICES:-}" ]; then',
        '    echo "[flash] fastboot 已连接；lsusb 可能显示为 18d1:d00d/Android Fastboot，而不是 3652 DFU。"',
        '  fi',
        '  if command -v lsusb >/dev/null 2>&1; then',
        '    usb_list="$(lsusb 2>/dev/null || true)"',
        '    if printf "%s\\n" "$usb_list" | grep -Eiq "3652:"; then',
        '      printf "%s\\n" "$usb_list" | grep -Ei "3652:" || true',
        '      if ! printf "%s\\n" "$usb_list" | grep -Eiq "3652:(6610|6615|6620|6625|6630|7610|7620|7630)"; then',
        '        echo "[WARN] 已看到 3652 USB 设备，但不是 3652:6610/66xx DFU；这通常还是运行态 USB，不能直接 fastboot 线刷。"',
        "      fi",
        '    elif printf "%s\\n" "$usb_list" | grep -Eiq "1a86:(8091|7523)"; then',
        '      printf "%s\\n" "$usb_list" | grep -Ei "1a86:(8091|7523)" || true',
        '      if [ -z "${FASTBOOT_DEVICES:-}" ]; then',
        '        echo "[WARN] 当前只看到 CH340 串口/HUB，没有看到 3652 DFU 或 fastboot；板子还没进入 S100 USB 线刷模式。"',
        "      else",
        '        echo "[flash] 同时看到 CH340 串口/HUB；当前以 fastboot 连接状态为准。"',
        "      fi",
        "    else",
        '      echo "[flash] lsusb 未看到 3652 DFU 或 CH340 线缆设备。"',
        "    fi",
        "  else",
        '    echo "[flash] 系统未安装 lsusb，跳过 USB 枚举摘要。"',
        "  fi",
        '  if compgen -G "/dev/ttyUSB*" >/dev/null; then',
        '    echo "[flash] 串口节点: $(ls /dev/ttyUSB* 2>/dev/null | tr "\\n" " ")"',
        '    if ! id -nG 2>/dev/null | tr " " "\\n" | grep -qx "dialout"; then',
        '      echo "[WARN] 当前用户不在 dialout 组，可能无法读取 CH340 串口日志。"',
        "    fi",
        "  fi",
        '  local drobot_rule="/etc/udev/rules.d/51-drobotics-usb.rules"',
        '  if command -v lsusb >/dev/null 2>&1 && lsusb 2>/dev/null | grep -Eiq "3652:"; then',
        '    if [ ! -f "$drobot_rule" ] || ! grep -q "idVendor}==\\"3652\\"" "$drobot_rule" 2>/dev/null; then',
        '      echo "[WARN] 未检测到 D-Robotics udev 规则；非 root 用户可能无法写入 3652 USB 设备。"',
        '      echo "[flash] 可安装工具内置规则: sudo cp resources/platform-tools/linux-x86_64/udev/rules.d/51-drobotics-usb.rules /etc/udev/rules.d/ && sudo udevadm control --reload-rules && sudo udevadm trigger"',
        "    fi",
        '    for dev in /sys/bus/usb/devices/*; do',
        '      [ -f "$dev/idVendor" ] || continue',
        '      [ "$(cat "$dev/idVendor" 2>/dev/null)" = "3652" ] || continue',
        '      local bus devnum node perms',
        '      bus="$(cat "$dev/busnum" 2>/dev/null || true)"',
        '      devnum="$(cat "$dev/devnum" 2>/dev/null || true)"',
        '      [ -n "$bus" ] && [ -n "$devnum" ] || continue',
        '      node="$(printf "/dev/bus/usb/%03d/%03d" "$bus" "$devnum")"',
        '      [ -e "$node" ] || continue',
        '      perms="$(stat -c "%A %U:%G" "$node" 2>/dev/null || true)"',
        '      echo "[flash] 3652 USB 权限: $node $perms"',
        '      [ -w "$node" ] || echo "[WARN] 当前用户对 $node 没有写权限，DFU/fastboot 可能失败；需要安装 udev 规则或以 root 运行刷写命令。"',
        "    done",
        "  fi",
        '  if command -v systemctl >/dev/null 2>&1 && systemctl is-active --quiet brltty 2>/dev/null; then',
        '    echo "[WARN] brltty 正在运行，可能抢占 CH340 串口；如 ttyUSB 反复断开，需要先停用 brltty。"',
        "  fi",
        '  if [ -n "${S100_REMOTE_HOST:-}" ] && command -v ip >/dev/null 2>&1; then',
        '    [ -n "${S100_REMOTE_HOST_CANDIDATES:-}" ] && echo "[flash] S100 SSH 候选地址: $S100_REMOTE_HOST_CANDIDATES"',
        '    local route_info=""',
        '    route_info="$(ip route get "$S100_REMOTE_HOST" 2>&1 || true)"',
        '    echo "[flash] S100 SSH 路由: ${route_info:-未返回}"',
        '    if printf "%s\\n" "$route_info" | grep -Eiq "unreachable|Network is unreachable"; then',
        '      echo "[WARN] 本机没有到 $S100_REMOTE_HOST 的可用路由；请先配置到目标网段的路由或切换到对应网络。"',
        '    elif printf "%s\\n" "$S100_REMOTE_HOST" | grep -Eq "^192\\.168\\.168\\."; then',
        '      if printf "%s\\n" "$route_info" | grep -q "via 192.168.234.1"; then',
        '        echo "[flash] 已检测到 192.168.168.0/24 目标经 192.168.234.1 转发；若 SSH 仍不通，优先检查 192.168.234.1 到 S100 的内网链路/上电状态。"',
        '      else',
        '        echo "[WARN] 未检测到经 192.168.234.1 访问 192.168.168.x 的路由；常见配置: sudo ip route replace 192.168.168.0/24 via 192.168.234.1"',
        "      fi",
        "    fi",
        "  fi",
        '  if [ -z "${FASTBOOT_DEVICES:-}" ] && ! printf "%s\\n" "${DFU_DEVICES:-}" | grep -Eiq "\\[3652:(6610|6615|6620|6625|6630|7610|7620|7630)\\]"; then',
        '    echo "[flash] 下一步：让 S100 进入线刷/DFU 模式，成功后应看到 3652:6610，或进入 fastboot 后 fastboot devices 有输出。"',
        "  fi",
        "}",
    ]


def s100_entry_help_lines() -> list[str]:
    return [
        's100_print_entry_help() {',
        '  echo "[flash] S100 进入刷写状态方法:"',
        '  echo "[flash] 1. 系统还能 SSH: 保持 Type-C 连接，执行线刷会自动尝试 sudo reboot usb2 -f。"',
        '  echo "[flash] 2. 系统不可达: 断电，按住 BOOT/RECOVERY/USB_BOOT，再上电或插 Type-C；看到 3652:6610 后松开。"',
        '  echo "[flash] 3. 判定标准: lsusb 看到 3652:6610，或 fastboot devices 有一台设备。只看到 CH340/ttyUSB 不是刷写态。"',
        '  echo "[flash] 4. 若完全无 USB 枚举: 换数据线/USB 口，确认板子供电和 Type-C 接在 S100 调试/USB 口。"',
        '  echo "[flash] 可用以下只读命令观察进入状态:"',
        '  printf "%s\\n" "[flash] watch -n 0.5 \'lsusb | grep -E \\"3652|1a86\\" || true; echo ---; fastboot devices\'"',
        "}",
    ]


def s100_entry_readiness_lines() -> list[str]:
    return [
        's100_report_entry_readiness() {',
        '  echo "[flash] S100 刷写入口就绪结论:"',
        '  if [ -n "${FASTBOOT_DEVICES:-}" ]; then',
        '    if [ -n "${BOOTINTF:-}" ]; then',
        '      case "$BOOTINTF" in',
        '        mmc)',
        '          if [ "${S100_HAS_EMMC_DISK:-0}" = "1" ]; then',
        '            echo "[flash] 结论: 已在 fastboot，bootintf=mmc 且包内有 eMMC 镜像；可以执行线刷。"',
        "          else",
        '            echo "[WARN] 结论: 已在 fastboot，bootintf=mmc，但预检未确认 disk/emmc_disk.simg；执行阶段会阻断。"',
        "          fi",
        "          ;;",
        '        scsi)',
        '          if [ "${S100_HAS_UFS_DISK:-0}" = "1" ]; then',
        '            echo "[flash] 结论: 已在 fastboot，bootintf=scsi 且包内有 UFS 镜像；可以执行线刷。"',
        "          else",
        '            echo "[WARN] 结论: 已在 fastboot，bootintf=scsi，但预检未确认 disk/ufs_disk.simg；执行阶段会阻断。"',
        "          fi",
        "          ;;",
        '        *)',
        '          echo "[WARN] 结论: 已在 fastboot，但 bootintf=$BOOTINTF 暂不支持；执行阶段会阻断。"',
        "          ;;",
        "      esac",
        "    else",
        '      echo "[WARN] 结论: 已在 fastboot，但未读取到 bootintf；执行阶段会阻断，需重新进入 fastboot 或检查 USB。"',
        "    fi",
        "    return 0",
        "  fi",
        '  if printf "%s\\n" "${DFU_DEVICES:-}" | grep -Eiq "\\[3652:6610\\]"; then',
        '    echo "[flash] 结论: 已在 S100 BootROM DFU 3652:6610；可以执行线刷，工具会先 DFU 引导到 fastboot。"',
        "    return 0",
        "  fi",
        '  if printf "%s\\n" "${DFU_DEVICES:-}" | grep -Eiq "\\[3652:(6615|6620|6625|6630|7610|7620|7630)\\]"; then',
        '    echo "[WARN] 结论: 检测到 D-Robotics DFU 中间阶段，但不是 3652:6610；建议重新上电进入 BootROM DFU。"',
        "    return 0",
        "  fi",
        '  if [ "${S100_SSH_PORT_OPEN:-0}" = "1" ] && command -v sshpass >/dev/null 2>&1; then',
        '    echo "[flash] 结论: 当前未在 USB 刷写态，但 SSH 端口和 sshpass 可用；执行线刷时会尝试 reboot usb2 -f。"',
        "    return 0",
        "  fi",
        '  echo "[WARN] 结论: 当前未检测到 fastboot/3652 DFU，且不能确认 SSH 自动进入；需要手动按 BOOT/RECOVERY 进入 3652:6610。"',
        "  s100_print_entry_help",
        "}",
    ]
