from __future__ import annotations


def s100_fastboot_recovery_lines() -> list[str]:
    return [
        's100_fastboot_getvar() {',
        '  local key="$1"',
        '  local raw=""',
        '  local value=""',
        '  raw="$(timeout 10 "$FASTBOOT_BIN" getvar "$key" 2>&1 || true)"',
        '  value="$(printf "%s\\n" "$raw" | awk -v key="$key" \'',
        '    /FAILED|remote:|Finished/ { next }',
        '    {',
        '      line=$0',
        '      sub("\\r$", "", line)',
        '      pattern=key ":"',
        '      if (index(line, pattern)) {',
        '        sub(".*" pattern "[[:space:]]*", "", line)',
        '        split(line, parts, /[[:space:]]+/)',
        '        print parts[1]',
        '        exit',
        '      }',
        '    }',
        '  \')"',
        '  case "$value" in ""|FAILED|OKAY|Finished|Finished.) return 1 ;; esac',
        '  printf "%s\\n" "$value"',
        "}",
        's100_bootintf_from_storage() {',
        '  case "$1" in',
        '    emmc|mmc) printf "%s\\n" "mmc" ;;',
        '    ufs|scsi) printf "%s\\n" "scsi" ;;',
        '    *) return 1 ;;',
        '  esac',
        "}",
        's100_select_bootintf() {',
        '  BOOTINTF="$(s100_fastboot_getvar bootintf || true)"',
        '  if [ -z "$BOOTINTF" ]; then',
        '    s100_reset_fastboot_usb || true',
        '    FASTBOOT_DEVICES="$("$FASTBOOT_BIN" devices || true)"',
        '    BOOTINTF="$(s100_fastboot_getvar bootintf || true)"',
        "  fi",
        '  S100_BOOTINTF_SOURCE="device"',
        '  case "$BOOTINTF" in',
        '    mmc|scsi) return 0 ;;',
        '    "") ;;',
        '    *) echo "[WARN] 忽略 fastboot 返回的异常 bootintf: $BOOTINTF"; BOOTINTF="" ;;',
        '  esac',
        '  S100_BOOTINTF_SOURCE=""',
        '  local storage_override="${DOG_REMOTE_TOOL_S100_STORAGE_TYPE:-}"',
        '  if [ -n "$storage_override" ]; then',
        '    BOOTINTF="$(s100_bootintf_from_storage "$storage_override" || true)"',
        '    if [ -z "$BOOTINTF" ]; then',
        '      echo "[ERROR] 不支持的 DOG_REMOTE_TOOL_S100_STORAGE_TYPE: $storage_override；可用值: emmc 或 ufs。"',
        '      return 2',
        '    fi',
        '    S100_BOOTINTF_SOURCE="override"',
        '    echo "[WARN] 未从设备读取到 bootintf，按手动指定介质继续: DOG_REMOTE_TOOL_S100_STORAGE_TYPE=$storage_override -> bootintf=$BOOTINTF"',
        '    return 0',
        '  fi',
        '  local has_emmc=0',
        '  local has_ufs=0',
        '  [ -f disk/emmc_disk.simg ] && has_emmc=1',
        '  [ -f disk/ufs_disk.simg ] && has_ufs=1',
        '  if [ "$has_emmc" = "1" ] && [ "$has_ufs" != "1" ]; then',
        '    BOOTINTF="mmc"',
        '    S100_BOOTINTF_SOURCE="package"',
        '    echo "[WARN] 未从设备读取到 bootintf；当前包只包含 eMMC 整盘镜像，按 bootintf=mmc 继续。"',
        '    return 0',
        '  fi',
        '  if [ "$has_ufs" = "1" ] && [ "$has_emmc" != "1" ]; then',
        '    BOOTINTF="scsi"',
        '    S100_BOOTINTF_SOURCE="package"',
        '    echo "[WARN] 未从设备读取到 bootintf；当前包只包含 UFS 整盘镜像，按 bootintf=scsi 继续。"',
        '    return 0',
        '  fi',
        '  return 1',
        "}",
        's100_reset_fastboot_usb() {',
        '  if ! command -v usbreset >/dev/null 2>&1 || ! command -v lsusb >/dev/null 2>&1; then',
        '    echo "[WARN] fastboot getvar 无响应，且本机没有 usbreset/lsusb，无法自动重置 USB。"',
        "    return 1",
        "  fi",
        '  local fastboot_nodes=""',
        '  fastboot_nodes="$(lsusb 2>/dev/null | sed -nE \'s/^Bus ([0-9]+) Device ([0-9]+): ID 18d1:d00d .*/\\1\\/\\2/p\')"',
        '  local fastboot_count=""',
        '  fastboot_count="$(printf "%s\\n" "$fastboot_nodes" | sed \'/^$/d\' | wc -l | tr -d " ")"',
        '  if [ "${fastboot_count:-0}" -ne 1 ]; then',
        '    echo "[WARN] fastboot getvar 无响应，且未检测到唯一 18d1:d00d USB fastboot 设备，跳过自动 USB reset。"',
        "    return 1",
        "  fi",
        '  local node=""',
        '  node="$(printf "%s\\n" "$fastboot_nodes" | sed \'/^$/d\' | head -1)"',
        '  echo "[WARN] fastboot getvar 无响应，尝试 USB reset: $node"',
        '  usbreset "$node" >/dev/null 2>&1 || { echo "[WARN] USB reset 失败: $node"; return 1; }',
        "  sleep 3",
        "  return 0",
        "}",
    ]
