from __future__ import annotations

from typing import Protocol

from dog_remote_tool.core.shell import quote
from dog_remote_tool.modules.ota.flash_package import S100_BOOT_SECURITY_FILES
from dog_remote_tool.modules.ota.flash_s100_entry import s100_entry_help_lines, s100_usb_diagnosis_lines
from dog_remote_tool.modules.ota.flash_s100_remote import (
    s100_password_ssh_options,
    s100_remote_probe_lines,
    s100_remote_setup_lines,
)


class S100DfuTarget(Protocol):
    key: str
    host: str
    user: str
    password: str


def s100_dfu_boot_lines(target: S100DfuTarget) -> list[str]:
    secure_ohp = " ".join(quote(path) for path in S100_BOOT_SECURITY_FILES["secure_ohp"])
    secure = " ".join(quote(path) for path in S100_BOOT_SECURITY_FILES["secure"])
    nosecure = " ".join(quote(path) for path in S100_BOOT_SECURITY_FILES["nosecure"])
    return [
        *s100_remote_setup_lines(target),
        *s100_remote_probe_lines(),
        *s100_entry_help_lines(),
        *s100_usb_diagnosis_lines(),
        'wait_for_fastboot() {',
        '  local timeout="${1:-45}"',
        '  local deadline=$(( $(date +%s) + timeout ))',
        '  while [ "$(date +%s)" -le "$deadline" ]; do',
        '    if [ -n "$("$FASTBOOT_BIN" devices || true)" ]; then',
        "      return 0",
        "    fi",
        "    sleep 1",
        "  done",
        "  return 1",
        "}",
        'set_dfu_path_from_output() {',
        '  local output="$1"',
        '  local paths count',
        '  paths="$(printf "%s\\n" "$output" | sed -nE \'s/.*\\[3652:(6610|6615|6620|6625|6630|7610|7620|7630)\\].*path="([^"]+)".*/\\2/p\' | sort -u)"',
        '  count="$(printf "%s\\n" "$paths" | sed \'/^$/d\' | wc -l | tr -d " ")"',
        '  if [ "$count" -gt 1 ]; then',
        '    echo "[ERROR] 检测到多个 D-Robotics DFU USB 路径，请只连接一台待刷 S100。"',
        '    printf "%s\\n" "$paths"',
        "    exit 2",
        "  fi",
        '  DFU_PATH="$(printf "%s\\n" "$paths" | sed \'/^$/d\' | head -1)"',
        "}",
        'wait_for_dfu_pid() {',
        "  local pid=\"$1\"",
        '  local timeout="${2:-45}"',
        '  local deadline=$(( $(date +%s) + timeout ))',
        '  local out=""',
        '  while [ "$(date +%s)" -le "$deadline" ]; do',
        '    out="$("$DFU_BIN" -l 2>&1 || true)"',
        '    if printf "%s\\n" "$out" | grep -Eiq "\\[3652:${pid}\\]"; then',
        '      set_dfu_path_from_output "$out"',
        "      return 0",
        "    fi",
        "    sleep 1",
        "  done",
        '  echo "[ERROR] 等待 DFU 设备 3652:${pid} 超时。"',
        '  printf "%s\\n" "$out" | tail -40',
        "  return 1",
        "}",
        'dfu_download() {',
        "  local file=\"$1\"",
        "  shift",
        '  local cmd=("$DFU_BIN" -D "$file" "$@")',
        '  if [ -n "${DFU_PATH:-}" ]; then',
        '    cmd+=(-p "$DFU_PATH")',
        "  fi",
        '  echo "[flash] DFU 下载: $file ${cmd[*]:3}"',
        '  local out=""',
        '  if ! out="$("${cmd[@]}" 2>&1)"; then',
        '    printf "%s\\n" "$out"',
        '    echo "[ERROR] DFU 下载失败: $file"',
        "    return 1",
        "  fi",
        '  printf "%s\\n" "$out"',
        '  if ! printf "%s\\n" "$out" | grep -q "Download done"; then',
        '    echo "[ERROR] DFU 输出未确认 Download done: $file"',
        "    return 1",
        "  fi",
        "}",
        'dfu_stage() {',
        '  local pid="$1"',
        '  local file="$2"',
        "  shift 2",
        '  if ! wait_for_dfu_pid "$pid" 45; then',
        '    if [ "$pid" = "6615" ] && [ "${S100_BOOT_SECURITY:-}" = "secure_ohp" ]; then',
        '      echo "[WARN] secure_ohp 引导后未进入 3652:6615；这通常表示板端不接受 OHP 安全引导或 USB 重新枚举失败。"',
        '      echo "[flash] 可断电重新进入 3652:6610 后设置 DOG_REMOTE_TOOL_S100_BOOT_SECURITY=secure 再试。"',
        "    fi",
        "    return 1",
        "  fi",
        '  dfu_download "$file" "$@" || return 1',
        "}",
        's100_select_boot_security() {',
        '  local boot_root="${S100_BOOT_ROOT:-.}"',
        '  S100_BOOT_SECURITY="${DOG_REMOTE_TOOL_S100_BOOT_SECURITY:-}"',
        '  if [ -z "$S100_BOOT_SECURITY" ]; then',
        '    if [ "${TARGET_KEY:-}" = "zg_surround_s100" ] && [ -f "$boot_root/xmodem_tools/sec/out/s100/cmd_load_hsmfw" ]; then',
        '      S100_BOOT_SECURITY="secure"',
        '    elif [ -f "$boot_root/xmodem_tools/sec/out/s100/cmd_load_hsmfw_ohp" ]; then',
        '      S100_BOOT_SECURITY="secure_ohp"',
        '    elif [ -f "$boot_root/xmodem_tools/sec/out/s100/cmd_load_hsmfw" ]; then',
        '      S100_BOOT_SECURITY="secure"',
        "    else",
        '      S100_BOOT_SECURITY="nosecure"',
        "    fi",
        "  fi",
        '  case "$S100_BOOT_SECURITY" in',
        '    secure_ohp) S100_BOOT_FILES=(' + secure_ohp + ") ;;",
        '    secure) S100_BOOT_FILES=(' + secure + ") ;;",
        '    nosecure) S100_BOOT_FILES=(' + nosecure + ") ;;",
        '    *) echo "[ERROR] 不支持的 DOG_REMOTE_TOOL_S100_BOOT_SECURITY: $S100_BOOT_SECURITY"; exit 2 ;;',
        "  esac",
        '  S100_BOOT_FILE_PATHS=()',
        '  for boot_file in "${S100_BOOT_FILES[@]}"; do',
        '    local boot_path="$boot_root/$boot_file"',
        '    test -f "$boot_path" || { echo "[ERROR] S100 DFU 引导缺少文件: $boot_path"; exit 2; }',
        '    S100_BOOT_FILE_PATHS+=("$boot_path")',
        "  done",
        '  S100_BOOT_FILES=("${S100_BOOT_FILE_PATHS[@]}")',
        '  echo "[flash] S100 DFU 引导安全类型: $S100_BOOT_SECURITY"',
        "}",
        's100_try_remote_reboot_to_flash() {',
        '  if [ "${DOG_REMOTE_TOOL_S100_AUTO_REBOOT:-1}" = "0" ]; then',
        '    echo "[flash] 已禁用自动 SSH 进入刷写状态，跳过远程 reboot usb2 -f。"',
        "    return 1",
        "  fi",
        '  if [ -z "$S100_REMOTE_HOST" ] || [ -z "$S100_REMOTE_USER" ] || [ -z "$S100_REMOTE_PASSWORD" ]; then',
        '    echo "[flash] 未配置 S100 SSH 信息，无法自动进入刷写状态。"',
        "    return 1",
        "  fi",
        '  if ! command -v sshpass >/dev/null 2>&1; then',
        '    echo "[WARN] 未安装 sshpass，无法自动通过 SSH 发送 reboot usb2 -f。"',
        "    return 1",
        "  fi",
        '  if ! s100_select_reachable_remote_host; then',
        '    echo "[WARN] 未找到可 SSH 登录的 S100 地址，无法自动进入刷写状态。"',
        "    return 1",
        "  fi",
        '  local quoted_password=""',
        '  printf -v quoted_password "%q" "$S100_REMOTE_PASSWORD"',
        '  local ssh_timeout="${DOG_REMOTE_TOOL_S100_SSH_TIMEOUT:-12}"',
        '  echo "[flash] 未检测到 fastboot/DFU，尝试通过 SSH 让 S100 进入刷写状态: $S100_REMOTE_USER@$S100_REMOTE_HOST"',
        f'  timeout "$ssh_timeout" sshpass -p "$S100_REMOTE_PASSWORD" ssh {s100_password_ssh_options(3)} "$S100_REMOTE_USER@$S100_REMOTE_HOST" "SUDO_PASSWORD=$quoted_password bash -lc \'printf \\"%s\\\\n\\" \\"\\$SUDO_PASSWORD\\" | sudo -S -p \\"\\" reboot usb2 -f >/dev/null 2>&1 || reboot usb2 -f >/dev/null 2>&1\'" >/dev/null 2>&1 || true',
        '  echo "[flash] 已尝试发送 SSH 进入刷写状态命令，等待 USB 重新枚举..."',
        '  sleep 3',
        "}",
        's100_dfu_boot_to_fastboot() {',
        '  FASTBOOT_DEVICES="$("$FASTBOOT_BIN" devices || true)"',
        '  if [ -n "$FASTBOOT_DEVICES" ]; then',
        '    s100_select_boot_security',
        '    echo "[flash] 已处于 fastboot，跳过 DFU 引导。"',
        "    return 0",
        "  fi",
        '  DFU_PATH=""',
        '  DFU_DEVICES="$("$DFU_BIN" -l 2>&1 || true)"',
        '  s100_report_usb_state',
        '  if ! printf "%s\\n" "$DFU_DEVICES" | grep -Eiq "\\[3652:6610\\]"; then',
        '    s100_try_remote_reboot_to_flash || true',
        '    if wait_for_fastboot 30; then',
        '      echo "[flash] SSH 触发后已进入 fastboot。"',
        "      return 0",
        "    fi",
        '    DFU_DEVICES="$("$DFU_BIN" -l 2>&1 || true)"',
        "  fi",
        '  if ! wait_for_dfu_pid "6610" 45; then',
        '    echo "[ERROR] 未检测到 S100 BootROM DFU 设备。请确认只连接一台 S100，且设备处于线刷/DFU 模式。"',
        "    s100_print_entry_help",
        "    return 1",
        "  fi",
        "  s100_select_boot_security",
        '  if [ "$S100_BOOT_SECURITY" = "nosecure" ]; then',
        '    dfu_stage "6610" "${S100_BOOT_FILES[0]}" -d,3652:6610 -a 0',
        '    dfu_stage "6610" "${S100_BOOT_FILES[1]}" -d,3652:6610 -a 0',
        '    dfu_stage "6610" "${S100_BOOT_FILES[2]}" -d,3652:6610 -a 0',
        '    dfu_stage "6620" "${S100_BOOT_FILES[3]}" -d,3652:6620 -a 0 -R',
        '    dfu_stage "6620" "${S100_BOOT_FILES[4]}" -d,3652:6620 -a 0 -R',
        '    dfu_stage "6625" "${S100_BOOT_FILES[5]}" -d,3652:6625 -a 0',
        '    dfu_stage "6625" "${S100_BOOT_FILES[6]}" -d,3652:6625 -a 1',
        '    dfu_stage "6625" "${S100_BOOT_FILES[7]}" -d,3652:6625 -a 2',
        '    dfu_stage "6625" "${S100_BOOT_FILES[8]}" -d,3652:6625 -a 3 -R',
        "  else",
        '    dfu_stage "6610" "${S100_BOOT_FILES[0]}" -d,3652:6610 -a 0',
        '    dfu_stage "6610" "${S100_BOOT_FILES[1]}" -d,3652:6610 -a 0',
        '    dfu_stage "6610" "${S100_BOOT_FILES[2]}" -d,3652:6610 -a 0',
        '    dfu_stage "6615" "${S100_BOOT_FILES[3]}" -d,3652:6615 -a 0 -R',
        '    dfu_stage "6615" "${S100_BOOT_FILES[4]}" -d,3652:6615 -a 0 -R',
        '    dfu_stage "6615" "${S100_BOOT_FILES[5]}" -d,3652:6615 -a 0 -R',
        '    dfu_stage "6615" "${S100_BOOT_FILES[6]}" -d,3652:6615 -a 0 -R',
        '    dfu_stage "6620" "${S100_BOOT_FILES[7]}" -d,3652:6620 -a 0 -R',
        '    dfu_stage "6620" "${S100_BOOT_FILES[8]}" -d,3652:6620 -a 0 -R',
        '    dfu_stage "6625" "${S100_BOOT_FILES[9]}" -d,3652:6625 -a 0',
        '    dfu_stage "6625" "${S100_BOOT_FILES[10]}" -d,3652:6625 -a 1',
        '    dfu_stage "6625" "${S100_BOOT_FILES[11]}" -d,3652:6625 -a 2',
        '    dfu_stage "6625" "${S100_BOOT_FILES[12]}" -d,3652:6625 -a 3 -R',
        "  fi",
        '  echo "[flash] 等待 S100 fastboot 枚举..."',
        '  wait_for_fastboot 60',
        "}",
        "s100_dfu_boot_to_fastboot",
    ]
