from __future__ import annotations

from dog_remote_tool.core.shell import quote
from dog_remote_tool.modules.ota.flash_package import S100_BOOT_SECURITY_FILES


def s100_package_precheck_lines() -> list[str]:
    secure_ohp = " ".join(quote(path) for path in S100_BOOT_SECURITY_FILES["secure_ohp"])
    secure = " ".join(quote(path) for path in S100_BOOT_SECURITY_FILES["secure"])
    nosecure = " ".join(quote(path) for path in S100_BOOT_SECURITY_FILES["nosecure"])
    return [
        's100_check_extracted_tree() {',
        '  local tree_root="$1"',
        '  local flash_dir=""',
        '  flash_dir="$(find -L "$tree_root" -path "*/product/img_packages/flash_all.sh" -printf "%h\\n" -quit 2>/dev/null || true)"',
        '  if [ -z "$flash_dir" ]; then',
        "    return 1",
        "  fi",
        '  local product_root=""',
        '  product_root="$(dirname "$flash_dir")"',
        '  test -d "$product_root/xmodem_tools" || { echo "[ERROR] S100 包已解压但缺少 DFU 引导目录: $product_root/xmodem_tools"; return 2; }',
        '  local missing=""',
        '  for required in flash_all.sh fpt.img HSM_FW.img HSM_RCA.img keyimage_ohp.img SBL.img scp.img spl.img MCU_S100_V1.0.img misc.img disk/miniboot_flash.img disk/miniboot_flash_nose.img system.img; do',
        '    test -f "$flash_dir/$required" || missing="$missing $required"',
        "  done",
        '  if [ -n "$missing" ]; then',
        '    echo "[ERROR] S100 包已解压但缺少线刷依赖:$missing"',
        "    return 2",
        "  fi",
        '  local boot_security=""',
        '  if [ -n "${DOG_REMOTE_TOOL_S100_BOOT_SECURITY:-}" ]; then',
        '    boot_security="$DOG_REMOTE_TOOL_S100_BOOT_SECURITY"',
        '  elif [ "${TARGET_KEY:-}" = "zg_surround_s100" ] && [ -f "$product_root/xmodem_tools/sec/out/s100/cmd_load_hsmfw" ]; then',
        '    boot_security="secure"',
        '  elif [ -f "$product_root/xmodem_tools/sec/out/s100/cmd_load_hsmfw_ohp" ]; then',
        '    boot_security="secure_ohp"',
        '  elif [ -f "$product_root/xmodem_tools/sec/out/s100/cmd_load_hsmfw" ]; then',
        '    boot_security="secure"',
        "  else",
        '    boot_security="nosecure"',
        "  fi",
        '  local boot_files=()',
        '  case "$boot_security" in',
        '    secure_ohp) boot_files=(' + secure_ohp + ") ;;",
        '    secure) boot_files=(' + secure + ") ;;",
        '    nosecure) boot_files=(' + nosecure + ") ;;",
        '    *) echo "[ERROR] 不支持的 DOG_REMOTE_TOOL_S100_BOOT_SECURITY: $boot_security"; return 2 ;;',
        "  esac",
        '  local missing_boot=""',
        '  for boot_file in "${boot_files[@]}"; do',
        '    test -f "$product_root/$boot_file" || missing_boot="$missing_boot $boot_file"',
        "  done",
        '  if [ -n "$missing_boot" ]; then',
        '    echo "[ERROR] S100 DFU 引导缺少文件:$missing_boot"',
        "    return 2",
        "  fi",
        '  echo "[flash] S100 DFU 引导文件校验: $boot_security (${#boot_files[@]} 个文件)"',
        '  if [ -f "$flash_dir/disk/emmc_disk.simg" ]; then',
        '    S100_HAS_EMMC_DISK=1',
        '    echo "[flash] S100 包结构校验: 已找到 eMMC 整盘镜像 disk/emmc_disk.simg"',
        "  fi",
        "  if [ -f \"$flash_dir/disk/ufs_disk.simg\" ]; then",
        '    S100_HAS_UFS_DISK=1',
        '    echo "[flash] S100 包结构校验: 已找到 UFS 整盘镜像 disk/ufs_disk.simg"',
        "  fi",
        '  if [ "$S100_HAS_EMMC_DISK" != "1" ] && [ "$S100_HAS_UFS_DISK" != "1" ]; then',
        '    echo "[WARN] S100 包结构校验: 未找到 disk/emmc_disk.simg 或 disk/ufs_disk.simg，执行线刷时会按 bootintf 再次阻断。"',
        "  fi",
        '  echo "[flash] S100 包结构校验: $flash_dir"',
        "  return 0",
        "}",
        's100_report_package_structure() {',
        '  local package_stem="$PACKAGE"',
        '  package_stem="${package_stem%.tar.gz}"',
        '  package_stem="${package_stem%.tgz}"',
        '  local sibling_tree="${package_stem}_extracted"',
        '  if [ -d "$sibling_tree" ]; then',
        '    echo "[flash] 检查已解压目录: $sibling_tree"',
        '    if s100_check_extracted_tree "$sibling_tree"; then',
        "      return 0",
        "    else",
        '      local rc="$?"',
        '      [ "$rc" -eq 2 ] && return 2',
        "    fi",
        "  fi",
        '  local root="${XDG_CACHE_HOME:-$HOME/.cache}/dog_remote_tool/line_flash"',
        '  local pkg_key=""',
        '  pkg_key="$(stat -c "%s_%Y" "$PACKAGE" | sha256sum | cut -c1-16)"',
        '  local pkg_base=""',
        '  pkg_base="$(basename "$PACKAGE")"',
        '  pkg_base="${pkg_base%.tar.gz}"',
        '  pkg_base="${pkg_base%.tgz}"',
        '  local cached_tree="$root/${pkg_base}_${pkg_key}"',
        '  if [ -d "$cached_tree/.complete" ]; then',
        '    echo "[flash] 检查线刷缓存目录: $cached_tree"',
        '    if s100_check_extracted_tree "$cached_tree"; then',
        "      return 0",
        "    else",
        '      local rc="$?"',
        '      [ "$rc" -eq 2 ] && return 2',
        "    fi",
        "  fi",
        '  echo "[flash] 未找到可复用的已解压 S100 包目录；执行线刷时会先解压并完整校验包结构。"',
        '  if [ "${DOG_REMOTE_TOOL_S100_TAR_LIST_CHECK:-0}" = "1" ]; then',
        '    local tar_timeout="${DOG_REMOTE_TOOL_S100_TAR_LIST_TIMEOUT:-300}"',
        '    local manifest=""',
        '    manifest="$(mktemp)"',
        '    echo "[flash] 开始读取 tar 清单做深度校验，超时 ${tar_timeout}s..."',
        '    if timeout "$tar_timeout" tar -tzf "$PACKAGE" > "$manifest"; then',
        '      grep -Eq "(^|/)product/img_packages/flash_all\\.sh$" "$manifest" || { echo "[ERROR] tar 清单缺少 product/img_packages/flash_all.sh"; rm -f "$manifest"; return 2; }',
        '      grep -Eq "(^|/)product/xmodem_tools/" "$manifest" || { echo "[ERROR] tar 清单缺少 product/xmodem_tools/"; rm -f "$manifest"; return 2; }',
        '      grep -Eq "(^|/)product/img_packages/system\\.img$" "$manifest" || { echo "[ERROR] tar 清单缺少 product/img_packages/system.img"; rm -f "$manifest"; return 2; }',
        '      grep -Eq "(^|/)product/img_packages/disk/emmc_disk\\.simg$" "$manifest" && S100_HAS_EMMC_DISK=1',
        '      grep -Eq "(^|/)product/img_packages/disk/ufs_disk\\.simg$" "$manifest" && S100_HAS_UFS_DISK=1',
        '      echo "[flash] S100 tar 清单校验通过。"',
        "    else",
        '      echo "[WARN] tar 清单校验超时或失败；大包可先完整解压为 包名_extracted 后再预检。"',
        "    fi",
        '    rm -f "$manifest"',
        "  else",
        '    echo "[flash] 如需强制读取 tar 清单，可设置 DOG_REMOTE_TOOL_S100_TAR_LIST_CHECK=1；大包可能耗时较长。"',
        "  fi",
        "}",
        "s100_report_package_structure",
    ]
