from __future__ import annotations


LAUNCH_NOTE_LABELS = {
    "spline_daemon": "样条轨迹",
    "imu_daemon": "IMU采集",
    "dog_task": "任务管理",
    "motion_control": "运动控制",
    "media_server": "媒体服务",
    "push_video": "视频推流",
    "push_image": "图像推流",
    "det_inference": "目标检测",
    "det-inference": "目标检测",
    "forward": "数据转发",
    "navigation": "导航",
    "nav2": "导航",
    "camera_calibration": "相机标定",
    "pose_calibration": "位姿标定",
    "self_check": "设备自检",
    "init_control": "初始化",
    "zero_calibration": "零点标定",
    "monitor": "健康监控",
    "delete_log": "日志清理",
    "bag_record": "录包",
    "record4patrol": "巡航录包",
    "stop-record": "停录包",
    "echo_nav_cmd": "导航命令",
    "time_sync": "时间同步",
    "time-sync": "时间同步",
    "zenoh_route": "通信路由",
    "zenoh-route": "通信路由",
    "ecal2ros": "协议桥",
    "app_node": "应用节点",
    "app-node": "社区节点",
    "lcm": "LCM监控",
    "power_daemon": "电源管理",
    "arc_platform": "回充平台",
    "remote_access": "公网远程",
    "remote-video": "远程视频",
    "remote_video": "远程视频",
    "image-decode": "图像解码",
    "image-decoder": "图像解码",
    "driver-gps": "GPS驱动",
    "driver-livox": "激光雷达",
    "driver-realsense": "相机驱动",
    "driver-odin": "奥丁雷达",
    "driver-rslidar": "激光雷达",
    "driver-uss": "超声驱动",
    "driver-imu": "IMU驱动",
    "driver-uwb": "UWB驱动",
    "driver-rtk": "RTK驱动",
    "mapping": "建图",
    "mapping-gps": "GPS建图",
    "mapping-multi": "多源建图",
    "mapping-elevation": "地形建图",
    "localization": "定位",
    "localization-gps": "GPS定位",
    "gps-tracking": "轨迹定位",
    "perception": "目标检测",
    "perception-seg": "语义分割",
    "robot-alg-manager": "算法管理",
    "realsense-ros-wrapper": "相机ROS",
    "data-collect": "数据采集",
    "data-collect-manager": "采集管理",
}


LAUNCH_NOTE_DETAILS = {
    "spline_daemon": "运行 spline_daemon，提供轨迹样条和插值能力。",
    "imu_daemon": "运行 imu_daemon，采集并转发 IMU 数据。",
    "dog_task": "启动 dog_task ROS 节点，管理机器人任务状态。",
    "motion_control": "启动 mc_ctrl，负责机器人运动控制。",
    "media_server": "启动 mediamtx，本地媒体/RTSP 服务。",
    "push_video": "等待 /dev/video11 后启动 video_stream 视频推流。",
    "push_image": "使用 ffmedia_stream 推送相机图像 RTSP 流。",
    "det_inference": "运行 detection_2d_node，执行视觉目标检测推理。",
    "det-inference": "运行 detection_2d_node，执行视觉目标检测推理。",
    "forward": "运行 robot_forward，桥接和转发机器人数据。",
    "navigation": "启动 robot_nav2 导航栈。",
    "nav2": "启动 robot_nav2 navigation_bringup 导航栈。",
    "camera_calibration": "运行单图相机标定工具。",
    "pose_calibration": "运行 pose_calib_test，执行位姿标定。",
    "self_check": "运行 device_check，执行设备自检。",
    "init_control": "运行 quad_control，进入初始化控制流程。",
    "zero_calibration": "运行 set_zero，执行零点标定。",
    "monitor": "运行 robot-monitor，监控机器人状态和故障。",
    "delete_log": "循环清理 /userdata/log 中超过保留期的日志。",
    "bag_record": "启动 ros2 bag record 录包。",
    "record4patrol": "按巡航/导航套餐启动 ros2 bag 录制。",
    "stop-record": "停止 ros2 bag 录制并归档相关日志。",
    "echo_nav_cmd": "使用 ecal_mon_cli 回显 nav_cmd 命令。",
    "time_sync": "启动 gpsd/chrony 并检查时间同步。",
    "time-sync": "启动 gpsd/chrony 并检查时间同步。",
    "zenoh_route": "运行 rmw_zenohd，提供 ROS 2 Zenoh 通信路由。",
    "zenoh-route": "运行 rmw_zenohd，提供 ROS 2 Zenoh 通信路由。",
    "ecal2ros": "运行 ecal2ros，桥接 eCAL 与 ROS 数据。",
    "app_node": "启动 kami_node 应用节点。",
    "app-node": "启动 community_node 社区/应用节点。",
    "lcm": "启动 lcm_spy_tui，用于 LCM/eCAL 相关监控。",
    "power_daemon": "运行 power_daemon，管理电源/电量状态。",
    "arc_platform": "运行 arc_platform，提供回充平台能力。",
    "remote_access": "启动 remote_access/frpc 公网远程连接。",
    "remote-video": "把本机 RTSP 视频转推到远程流媒体服务器。",
    "remote_video": "把本机 RTSP 视频转推到远程流媒体服务器。",
    "image-decode": "启动 image_decode，解码压缩图像流。",
    "image-decoder": "启动 image_decode，解码压缩图像流。",
    "driver-gps": "启动 GPS 驱动，当前 NX 使用 sixents_gps_driver。",
    "driver-livox": "启动 Livox 激光雷达驱动。",
    "driver-realsense": "启动 RealSense 相机驱动。",
    "driver-odin": "启动 Odin 雷达 ROS 驱动。",
    "driver-rslidar": "启动 rslidar_sdk 激光雷达驱动。",
    "driver-uss": "启动 uss_driver 超声驱动。",
    "driver-imu": "启动 imu_driver IMU 驱动。",
    "driver-uwb": "启动 uwb_driver UWB 驱动。",
    "driver-rtk": "启动 sixents_gps_driver RTK/GNSS 驱动。",
    "mapping": "启动普通建图流程。",
    "mapping-gps": "启动带 GPS/RTK 的建图流程。",
    "mapping-multi": "启动多源/多类型建图流程。",
    "mapping-elevation": "启动 height_map_generator 地形建图。",
    "localization": "启动 alg_manager 定位链路。",
    "localization-gps": "启动 GPS 定位流程。",
    "gps-tracking": "启动 GPS 轨迹定位/路径记录流程。",
    "perception": "运行 detection_2d_node 视觉检测。",
    "perception-seg": "运行 perception_jobs 语义/感知任务。",
    "robot-alg-manager": "运行 robot_alg_manager，管理导航/算法链路。",
    "realsense-ros-wrapper": "启动 RealSense ROS wrapper。",
    "data-collect": "按场景录制导航、定位、传感器等数据。",
    "data-collect-manager": "循环调度 data-collect 并归档日志。",
}
