from __future__ import annotations

from dog_remote_tool.core.profiles import ProductProfile
from dog_remote_tool.core.shell import CommandSpec, ssh_command


def package_filter_command() -> str:
    return (
        "("
        "dpkg-query -W -f='${binary:Package}\\t${Version}\\n' 2>/dev/null | "
        "awk -F '\\t' 'BEGIN{IGNORECASE=1} "
        "$1 ~ /^(app-|community-|det-|elevation-|libnvjpeg|robot|robots_|motion-control|driver-|navigation|perception-|zsibot)/ "
        "{print}'; "
        "python3 - <<'PY' 2>/dev/null\n"
        "from pathlib import Path\n"
        "\n"
        "INTERESTING_PREFIXES = (\n"
        "    'app-', 'community-', 'det-', 'elevation-', 'libnvjpeg', 'robot', 'robots_',\n"
        "    'motion-control', 'driver-', 'navigation', 'perception-', 'zsibot',\n"
        ")\n"
        "\n"
        "def emit_package(name, version):\n"
        "    name = (name or '').strip()\n"
        "    version = (version or '').strip()\n"
        "    if name and version and name.lower().startswith(INTERESTING_PREFIXES):\n"
        "        print(f'{name}\\t{version}')\n"
        "\n"
        "def read_kv(path):\n"
        "    data = {}\n"
        "    try:\n"
        "        lines = Path(path).read_text(errors='ignore').splitlines()\n"
        "    except OSError:\n"
        "        return data\n"
        "    for raw in lines:\n"
        "        if ':' not in raw or raw[:1].isspace():\n"
        "            continue\n"
        "        key, value = raw.split(':', 1)\n"
        "        value = value.strip().strip('\"').strip(\"'\")\n"
        "        if key and value:\n"
        "            data[key.strip()] = value\n"
        "    return data\n"
        "\n"
        "root = Path('/opt/robot/robot_version_manager')\n"
        "if root.is_dir():\n"
        "    for version_file in sorted(root.glob('*/version.yaml')):\n"
        "        meta = read_kv(version_file)\n"
        "        name = meta.get('name') or version_file.parent.name\n"
        "        version = meta.get('version')\n"
        "        emit_package(name, version)\n"
        "\n"
        "def read_release_manifest(path):\n"
        "    try:\n"
        "        lines = Path(path).read_text(errors='ignore').splitlines()\n"
        "    except OSError:\n"
        "        return\n"
        "    current = ''\n"
        "    for raw in lines:\n"
        "        if raw and not raw[:1].isspace() and raw.rstrip().endswith(':'):\n"
        "            current = raw.split(':', 1)[0].strip().strip('\"').strip(\"'\")\n"
        "            continue\n"
        "        line = raw.strip()\n"
        "        if current and line.startswith('version:'):\n"
        "            version = line.split(':', 1)[1].strip().strip('\"').strip(\"'\")\n"
        "            emit_package(current, version)\n"
        "\n"
        "runtime = read_kv('/opt/runtime/version')\n"
        "if runtime.get('Package') and runtime.get('Version'):\n"
        "    emit_package(runtime['Package'], runtime['Version'])\n"
        "\n"
        "release = read_kv('/opt/release/version.yaml')\n"
        "if release.get('version'):\n"
        "    print(f\"system-release\\t{release['version']}\")\n"
        "\n"
        "for release_file in sorted(Path('/etc/release').glob('*.yaml')):\n"
        "    read_release_manifest(release_file)\n"
        "for release_file in sorted(Path('/opt/release').glob('*.yaml')):\n"
        "    read_release_manifest(release_file)\n"
        "PY\n"
        "if command -v robot-launch >/dev/null 2>&1; then "
        "robot-launch --version 2>/dev/null | awk 'NF>=2 {print \"robot-launch\\t\" $NF; exit}'; "
        "fi"
        ") | awk -F '\\t' 'NF>=2 && !seen[$1]++ {print}' | sort -u | head -220"
    )


def probe_command(profile: ProductProfile) -> CommandSpec:
    package_filter = package_filter_command()
    inner = (
        "printf 'DOG_REMOTE_STATUS_BEGIN\\n'; "
        "printf 'HOSTNAME=%s\\n' \"$(hostname 2>/dev/null || true)\"; "
        "release_version=''; "
        "if [ -r /opt/release/version.yaml ]; then "
        "release_version=$(awk -F: '$1==\"version\" {gsub(/^[ \\t\\\"'\"'\"']+|[ \\t\\\"'\"'\"']+$/, \"\", $2); print $2; exit}' /opt/release/version.yaml 2>/dev/null); "
        "fi; "
        "if [ -z \"$release_version\" ] && [ -r /etc/user_release_version ]; then release_version=$(sed -n '1p' /etc/user_release_version 2>/dev/null); fi; "
        "if [ -z \"$release_version\" ]; then "
        "release_file=$(find /etc/release /opt/release -maxdepth 1 -type f -name '*.yaml' 2>/dev/null | "
        "grep -v '/rootfs_.*\\.yaml$' | grep -v '/version\\.yaml$' | sort | tail -1); "
        "[ -n \"$release_file\" ] && release_version=$(basename \"$release_file\" .yaml); "
        "fi; "
        "printf 'RELEASE=%s\\n' \"${release_version:-未找到}\"; "
        "printf 'PACKAGES_BEGIN\\n'; "
        f"{package_filter}; "
        "printf 'PACKAGES_END\\n'; "
        "printf 'LAUNCH_BEGIN\\n'; "
        "if command -v robot-launch >/dev/null 2>&1; then "
        "robot-launch list 2>/dev/null | sed -r 's/\\x1B\\[[0-9;]*[A-Za-z]//g' || true; "
        "else printf 'robot-launch not found\\n'; fi; "
        "printf 'LAUNCH_END\\n'; "
        "printf 'DOG_REMOTE_STATUS_END\\n'"
    )
    return CommandSpec("读取当前端版本与状态", ssh_command(profile, inner), concurrency="parallel")
